// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using bouffe.Models;

namespace bouffe.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.3.20181.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("bouffe.Interfaces.AMenuItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageThumbUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("InStock")
                        .HasColumnType("bit");

                    b.Property<string>("LongDesc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("ShortDesc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AMenuItem");

                    b.HasDiscriminator<string>("Discriminator").HasValue("AMenuItem");
                });

            modelBuilder.Entity("bouffe.Models.ChickenType", b =>
                {
                    b.Property<int>("ChickenTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ChickenTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChickenTypeId");

                    b.ToTable("ChickenTypes");
                });

            modelBuilder.Entity("bouffe.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("MenuItemId")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("bouffe.Models.PizzaType", b =>
                {
                    b.Property<int>("PizzaTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PizzaTypeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PizzaTypeId");

                    b.ToTable("PizzaTypes");
                });

            modelBuilder.Entity("bouffe.Models.Chicken", b =>
                {
                    b.HasBaseType("bouffe.Interfaces.AMenuItem");

                    b.Property<int>("ChickenTypeId")
                        .HasColumnType("int");

                    b.HasIndex("ChickenTypeId");

                    b.HasDiscriminator().HasValue("Chicken");
                });

            modelBuilder.Entity("bouffe.Models.Pizza", b =>
                {
                    b.HasBaseType("bouffe.Interfaces.AMenuItem");

                    b.Property<int>("PizzaTypeId")
                        .HasColumnType("int");

                    b.HasIndex("PizzaTypeId");

                    b.HasDiscriminator().HasValue("Pizza");
                });

            modelBuilder.Entity("bouffe.Models.OrderItem", b =>
                {
                    b.HasOne("bouffe.Interfaces.AMenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId");
                });

            modelBuilder.Entity("bouffe.Models.Chicken", b =>
                {
                    b.HasOne("bouffe.Models.ChickenType", "ChickenType")
                        .WithMany("Chickens")
                        .HasForeignKey("ChickenTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("bouffe.Models.Pizza", b =>
                {
                    b.HasOne("bouffe.Models.PizzaType", "PizzaType")
                        .WithMany("Pizzas")
                        .HasForeignKey("PizzaTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
